// Default HTML is copied from the original page. Keep keys stable when editing copy.
export const defaultContent = {
    "hero.label.1": "For OpenAI forward-deployed engineers",
    "hero.title": "\n            Ship customer apps and agents on one stack.\n          ",
    "hero.lede": "\n            You're dropping into customer environments and shipping in days, not quarters. The database, the API, the\n            agents and the frontend should live together: one region, one private network, one place to read the logs.\n            That's Render.\n          ",
    "why.label.1": "<span class=\"num\">01</span> The problem with stitching providers",
    "why.h2.1": "Four vendors per prototype is three too many.",
    "why.p.1": "\n              A typical \"edge-first\" build puts the frontend and functions on Vercel or Cloudflare, then bolts on a\n              database vendor, a queue vendor and a logging vendor. Each one is good at its slice. Together they add\n              network hops, dashboards, credentials and blind spots that you have to manage at every customer.\n            ",
    "why.h3.1": "<span class=\"tag\">Stitched</span> Edge platform + vendors",
    "why.li.1": "<div><strong>Frontend + functions</strong><span>Vercel / Cloudflare</span></div>",
    "why.li.2": "<div><strong>Database</strong><span>Separate database vendor</span></div>",
    "why.li.3": "<div><strong>Queue / background jobs</strong><span>Separate queue vendor</span></div>",
    "why.li.4": "<div><strong>Logs &amp; traces</strong><span>Separate logging vendor</span></div>",
    "why.p.2": "4 bills · 4 dashboards · 4 sets of credentials · traffic between them over the public internet",
    "why.h3.2": "<span class=\"tag tag--accent\">Render</span> One project",
    "why.p.3": "project: acme-agent · env: production · region: oregon",
    "why.li.5": "Static site",
    "why.li.6": "Web service",
    "why.li.7": "Private service",
    "why.li.8": "Worker",
    "why.li.9": "Cron job",
    "why.li.10": "Workflows",
    "why.li.11": "Postgres",
    "why.li.12": "Key Value",
    "why.p.4": "1 Blueprint · 1 dashboard · 1 private network · logs and metrics for every layer",
    "pn.label.1": "<span class=\"num\">02</span> Private networking",
    "pn.h2.1": "Keep the hot path off the public internet.",
    "pn.h3.1": "With a functions platform + external database",
    "pn.external.body": "\n                Your backend function runs on the platform's compute, in whatever region it defaults to unless you\n                pin one, and the database lives with a different provider, in its own network and often its own region.\n                Every query leaves one company's infrastructure, crosses the public internet and enters another's.\n                The database needs a public endpoint to make that work.\n              ",
    "pn.h3.2": "With Render",
    "pn.render.body": "\n                You pick the region, per customer. Your web service, private services, background workers and\n                Render Postgres / Key Value share a <strong>private network</strong> inside the same region and\n                workspace, and talk over internal hostnames like <code>api:10000</code> or\n                <code>acme-db</code>. Your database never has to be reachable from the internet.\n              ",
    "pn.figcaption.1": "<span class=\"dot dot--muted\" aria-hidden=\"true\"></span> Public internet path: long, many hops, three providers.",
    "pn.figcaption.2": "<span class=\"dot dot--accent\" aria-hidden=\"true\"></span> Render private network: short, contained in one region.",
    "pn.li.1": "<strong>Lower latency</strong><span>Services and data sit in the same region.</span>",
    "pn.li.2": "<strong>Fewer hops</strong><span>No round trip across providers for every query.</span>",
    "pn.li.3": "<strong>No public database</strong><span>Postgres and Key Value can stay internal-only.</span>",
    "obs.label.1": "<span class=\"num\">03</span> Observability",
    "obs.h2.1": "When a request dies in flight, see exactly where.",
    "obs.h3.1": "Across providers",
    "obs.p.1": "\n                That same cross-provider request can fail somewhere between the function and the database, and no one\n                notices. Each vendor sees only its own slice: the function logs a timeout, the database logs nothing\n                unusual, the queue never got the message. The failure lives in the gap between dashboards.\n              ",
    "obs.h3.2": "On Render",
    "obs.p.2": "\n                Logs and metrics cover every layer: web services, APIs, workers, cron jobs and Postgres, all in one\n                place. When something breaks <em>between</em> layers, you and your coding agent follow one request\n                end to end.\n              ",
    "obs.p.3": "\n                The <strong>Render CLI</strong> and <strong>Render MCP server</strong> let an agent pull logs and\n                metrics directly, so Codex or your agent of choice can triage a customer incident with you without\n                copying and pasting from four tabs.\n              ",
    "agents.label.1": "<span class=\"num\">04</span> Built for agents",
    "agents.h2.1": "Render is the best platform to deploy agentic apps.",
    "agents.p.1": "\n              Agents need two things serverless functions handle poorly: long-running, retryable, multi-step\n              execution, and a safe place to run the code they generate. Render provides both as first-class\n              primitives in the same project as the rest of your app: Workflows run in your region on its private\n              network, and Sandboxes keep generated code isolated from it.\n            ",
    "agents.h3.1": "Workflows <span class=\"kicker-sub\">durable agent runs</span>",
    "agents.li.1": "Define tasks as plain TypeScript or Python functions with the Render SDK.",
    "agents.li.2": "Start runs from your web service, another task or the API.",
    "agents.li.3": "Each run gets its own instance, retries automatically with backoff, can last up to 24 hours, and scales to zero when idle.",
    "agents.li.4": "Chain subtasks and fan out in parallel, with no separate queue or broker.",
    "agents.li.5": "Task runs reach your services and datastores in the same region over the private network.",
    "agents.h3.2": "Sandboxes <span class=\"kicker-sub\">isolated code execution</span> <span class=\"tag\">Early access</span>",
    "agents.li.6": "Ephemeral, isolated environments for untrusted or agent-generated code: install packages, write files, run scripts and tests.",
    "agents.li.7": "Your production infrastructure is never exposed to that code.",
    "agents.li.8": "Create them from the same Render SDK or CLI; terminate them when done or let them time out.",
    "agents.li.9": "Snapshots let you reuse a prepared environment.",
    "agents.figcaption.1": "\n              One request, one region: the web service starts a durable run, subtasks fan out over the private network,\n              and generated code runs in an isolated sandbox.\n            ",
    "agents.li.10": "<strong>Shared context</strong><span>The agent run, the code it executes, the API that started it and the Postgres it writes to live in one workspace and region, under one set of credentials and one SDK and CLI.</span>",
    "agents.li.11": "<strong>End-to-end visibility</strong><span>See Workflow run status next to the logs and metrics of the services it calls. A failure between API, agent run and database is traceable in one place, by you or your coding agent via the Render CLI or MCP.</span>",
    "agents.li.12": "<strong>Fewer moving parts</strong><span>No separate queue vendor, worker fleet or third-party code-execution provider to wire up and watch.</span>",
    "examples.label.1": "<span class=\"num\">05</span> Example apps",
    "examples.h2.1": "What FDEs actually build, and where it runs best.",
    "examples.p.1": "\n              Customer engagements tend to land on a few shapes. Each of them needs data next to compute, work that\n              outlives a request, or connections that stay open. Those are the things a full-stack platform is for.\n            ",
    "examples.h3.1": "Customer knowledge assistant <span class=\"tag\">RAG</span>",
    "examples.p.2": "Answer questions over a customer's docs, tickets and wikis, with citations.",
    "examples.li.1": "<span class=\"stack-kind\">web</span>Chat UI + API",
    "examples.li.2": "<span class=\"stack-kind\">postgres</span>Render Postgres with pgvector",
    "examples.li.3": "<span class=\"stack-kind\">workflow</span>Document ingestion + embedding",
    "examples.p.3": "<strong>Why Render, not Vercel:</strong> embeddings and similarity queries stay on the private network next to the data, and ingestion runs as a Workflow without serverless timeouts.",
    "examples.h3.2": "Long-running research / ops agent",
    "examples.p.4": "Multi-step, tool-calling agents that investigate, act and report back.",
    "examples.li.4": "<span class=\"stack-kind\">web</span>Starts runs, shows progress",
    "examples.li.5": "<span class=\"stack-kind\">workflow</span>Agent tasks with retries + backoff",
    "examples.li.6": "<span class=\"stack-kind\">sandbox</span>Runs tool code in isolation",
    "examples.li.7": "<span class=\"stack-kind\">postgres</span>Run history and artifacts",
    "examples.p.5": "<strong>Why Render, not Vercel:</strong> Workflow runs can last up to 24 hours, retry automatically and scale to zero, so agent runs outlive serverless function limits, and every step lands in the same logs.",
    "examples.h3.3": "Realtime voice / chat agent",
    "examples.p.6": "A support or field agent customers talk to, live, with sub-second turn-taking.",
    "examples.li.8": "<span class=\"stack-kind\">web</span>Holds WebSockets to the Realtime API",
    "examples.li.9": "<span class=\"stack-kind\">key value</span>Session state + presence",
    "examples.li.10": "<span class=\"stack-kind\">postgres</span>Transcripts and outcomes",
    "examples.p.7": "<strong>Why Render, not Vercel:</strong> long-lived connections need always-on processes, not short-lived edge or serverless functions.",
    "examples.h3.4": "Back-office automation &amp; evals pipeline",
    "examples.p.8": "Nightly pulls from customer systems, batch model calls and evals, results on a dashboard.",
    "examples.li.11": "<span class=\"stack-kind\">cron</span>Kicks off the nightly run",
    "examples.li.12": "<span class=\"stack-kind\">workflow</span>Fan-out batch calls + evals",
    "examples.li.13": "<span class=\"stack-kind\">postgres</span>Scores and outputs",
    "examples.li.14": "<span class=\"stack-kind\">web</span>Dashboard on top",
    "examples.p.9": "<strong>Why Render, not Vercel:</strong> scheduling, fan-out, storage and UI all live in one project and one region.",
    "gets.label.1": "<span class=\"num\">06</span> What an FDE gets",
    "gets.h2.1": "Everything a customer engagement needs, by default.",
    "gets.strong.1": "One <code>render.yaml</code> Blueprint",
    "gets.span.1": "The whole stack as code, in the region each customer needs. Fork it per customer.",
    "gets.strong.2": "Private networking by default",
    "gets.span.2": "Internal hostnames, no public database.",
    "gets.strong.3": "Unified logs and metrics",
    "gets.span.3": "Web, API, workers, cron and Postgres in one place.",
    "gets.strong.4": "Durable agent runs with Workflows",
    "gets.span.4": "Retries, fan-out and runs of up to 24 hours, scaling to zero.",
    "gets.strong.5": "Agent-friendly CLI and MCP",
    "gets.span.5": "Your coding agent can deploy, read logs and check metrics.",
    "start.label.1": "<span class=\"num\">07</span> Get started",
    "start.h2.1": "One file. Whole stack.",
    "start.p.1": "\n              A Blueprint describes the web service and the database it talks to, in one project environment.\n              Render wires the connection string over the private network. Commit it, connect the repo, and every\n              customer gets the same shape of stack.\n            ",
    "start.figcaption.1": "Illustrative render.yaml with a web service and Postgres in one project environment"
};
